import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { DocumentCheckIcon } from '@heroicons/react/24/outline';
import LoginLink from './components/LoginLink';

const fadeInUp = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 }
};

export default function TermsOfService() {
  return (
    <div className="flex flex-col min-h-screen bg-white text-gray-900">
      <header className="sticky top-0 bg-white/70 backdrop-blur-xl z-50 border-b border-white/40 shadow-sm">
        <nav className="max-w-7xl mx-auto flex items-center justify-between py-4 px-6">
          <Link to="/">
            <img src="/logo.png" alt="ClarifyOps" className="h-7" />
          </Link>
          <div className="hidden md:flex items-center gap-6 text-sm font-medium text-gray-700">
            <Link to="/" className="hover:text-blue-600 transition-colors">Home</Link>
            <Link to="/trust" className="hover:text-blue-600 transition-colors">Trust Center</Link>
            <Link to="/privacy" className="hover:text-blue-600 transition-colors">Privacy Policy</Link>
            <LoginLink source="terms" className="px-4 py-2 border border-gray-300 rounded-full hover:bg-gray-50">
              Log in
            </LoginLink>
          </div>
        </nav>
      </header>

      <main className="flex-1">
        <section className="bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 text-white py-16 px-6">
          <motion.div
            className="max-w-4xl mx-auto text-center"
            initial="hidden"
            animate="visible"
            variants={fadeInUp}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur px-4 py-2 rounded-full text-sm mb-6">
              <DocumentCheckIcon className="h-4 w-4 text-emerald-400" />
              <span>Legal Agreement</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
            <p className="text-gray-300">Last updated: February 5, 2026</p>
          </motion.div>
        </section>

        <section className="py-16 px-6">
          <div className="max-w-4xl mx-auto prose prose-lg prose-gray">
            <motion.div
              initial="hidden"
              animate="visible"
              variants={fadeInUp}
              transition={{ duration: 0.5, delay: 0.2 }}
            >
              <div className="bg-indigo-50 border border-indigo-200 rounded-xl p-6 mb-10 not-prose">
                <p className="text-indigo-800 font-medium">
                  Please read these Terms of Service ("Terms") carefully before using ClarifyOps. By accessing or using our 
                  platform, you agree to be bound by these Terms. If you do not agree to these Terms, do not use our services.
                </p>
              </div>

              <h2 className="text-2xl font-bold mt-10 mb-4">1. Definitions</h2>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
                <li><strong>"Platform"</strong> refers to the ClarifyOps web application, APIs, and related services.</li>
                <li><strong>"User"</strong> or <strong>"You"</strong> refers to any individual or entity that accesses or uses the Platform.</li>
                <li><strong>"Customer"</strong> refers to the organization that has entered into a subscription agreement with ClarifyOps.</li>
                <li><strong>"Content"</strong> refers to any data, documents, files, text, or other materials uploaded to or generated by the Platform.</li>
                <li><strong>"PHI"</strong> refers to Protected Health Information as defined under the Health Insurance Portability and Accountability Act (HIPAA).</li>
                <li><strong>"Covered Entity"</strong> refers to a healthcare provider, health plan, or healthcare clearinghouse as defined under HIPAA.</li>
              </ul>

              <h2 className="text-2xl font-bold mt-10 mb-4">2. Acceptance of Terms</h2>
              <p className="text-gray-700 mb-4">
                By creating an account or using ClarifyOps, you represent that you are at least 18 years old and have the 
                authority to bind yourself or your organization to these Terms. If you are using ClarifyOps on behalf of an 
                organization, you represent that you have the authority to bind that organization to these Terms.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">3. Description of Services</h2>
              <p className="text-gray-700 mb-4">
                ClarifyOps provides an AI-powered claims data extraction and management platform designed for insurance 
                and healthcare workflows. Our services include:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
                <li>AI-powered document parsing and data extraction from claims documents</li>
                <li>CPT/ICD code validation and classification</li>
                <li>Workflow automation and claims routing (OpsClaim)</li>
                <li>Fraud detection and risk scoring (AuditFlow)</li>
                <li>Reporting, analytics, and data export capabilities</li>
                <li>API access for integration with external systems</li>
                <li>AI assistant for claims processing guidance</li>
              </ul>

              <h2 className="text-2xl font-bold mt-10 mb-4">4. Account Registration and Security</h2>
              
              <h3 className="text-xl font-semibold mt-6 mb-3">4.1 Account Creation</h3>
              <p className="text-gray-700 mb-4">
                You must provide accurate and complete information when creating an account. You are responsible for 
                maintaining the confidentiality of your login credentials and for all activities that occur under your account.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">4.2 Account Security</h3>
              <p className="text-gray-700 mb-4">
                You must immediately notify ClarifyOps of any unauthorized use of your account or any other security breach. 
                We implement industry-standard security measures, including JWT-based authentication, bcrypt password hashing, 
                and role-based access controls.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">4.3 Access Roles</h3>
              <p className="text-gray-700 mb-4">
                Our platform supports multiple access roles (admin, viewer, broker, adjuster, medical reviewer, auditor). 
                Customers are responsible for assigning appropriate roles to their users in accordance with the principle 
                of least privilege and applicable HIPAA requirements.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">5. HIPAA Compliance and PHI</h2>
              
              <h3 className="text-xl font-semibold mt-6 mb-3">5.1 Business Associate Agreement</h3>
              <p className="text-gray-700 mb-4">
                If you are a Covered Entity or Business Associate under HIPAA and will use ClarifyOps to process PHI, 
                you must enter into a Business Associate Agreement (BAA) with ClarifyOps prior to uploading any PHI 
                to the Platform. Contact <a href="mailto:compliance@clarifyops.com" className="text-indigo-600 hover:underline">compliance@clarifyops.com</a> to 
                execute a BAA.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">5.2 Your HIPAA Obligations</h3>
              <p className="text-gray-700 mb-4">If you process PHI through ClarifyOps, you are responsible for:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
                <li>Ensuring you have obtained all necessary consents and authorizations from patients</li>
                <li>Providing only the minimum necessary PHI required for the intended purpose</li>
                <li>Configuring appropriate access controls for your team members</li>
                <li>Reporting any known or suspected breaches of PHI to ClarifyOps promptly</li>
                <li>Maintaining your own HIPAA compliance program</li>
              </ul>

              <h3 className="text-xl font-semibold mt-6 mb-3">5.3 Our HIPAA Commitments</h3>
              <p className="text-gray-700 mb-4">As a Business Associate, ClarifyOps will:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
                <li>Use and disclose PHI only as permitted by the BAA and applicable law</li>
                <li>Implement appropriate administrative, physical, and technical safeguards</li>
                <li>Report any security incidents or breaches involving PHI</li>
                <li>Ensure our subcontractors agree to equivalent protections</li>
                <li>Return or destroy PHI upon termination of the agreement</li>
                <li>Make our practices available for audit as required by HIPAA</li>
              </ul>

              <h2 className="text-2xl font-bold mt-10 mb-4">6. Your Content and Data</h2>
              
              <h3 className="text-xl font-semibold mt-6 mb-3">6.1 Ownership</h3>
              <p className="text-gray-700 mb-4">
                You retain all ownership rights to the Content you upload to ClarifyOps. We do not claim any ownership 
                rights over your data, documents, or claims information.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">6.2 License Grant</h3>
              <p className="text-gray-700 mb-4">
                By uploading Content, you grant ClarifyOps a limited, non-exclusive license to process, store, and 
                analyze your Content solely for the purpose of providing our services to you. This license terminates 
                when you delete your Content or close your account.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">6.3 Data Isolation</h3>
              <p className="text-gray-700 mb-4">
                All data is isolated by tenant. Your Content is never accessible to other customers of ClarifyOps. 
                We implement tenant-scoped queries across all database operations to ensure complete data separation.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">6.4 Data Portability</h3>
              <p className="text-gray-700 mb-4">
                You may export your data at any time using our built-in export tools (Excel, PDF, CSV formats). 
                Upon account termination, you will have 30 days to export your data before it is permanently deleted.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">7. AI Processing and Third-Party Services</h2>
              
              <h3 className="text-xl font-semibold mt-6 mb-3">7.1 AI-Powered Features</h3>
              <p className="text-gray-700 mb-4">
                ClarifyOps uses artificial intelligence to extract data from documents, classify claims, detect fraud indicators, 
                and generate summaries. AI-generated results should be reviewed by qualified personnel before being used for 
                decision-making. ClarifyOps does not guarantee the accuracy of AI-extracted data.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">7.2 Third-Party AI Services</h3>
              <p className="text-gray-700 mb-4">
                We use OpenRouter to access AI models for document processing. Before sending data to external AI services, 
                our system automatically detects and redacts PHI identifiers to minimize exposure. Despite these precautions, 
                you acknowledge that the use of third-party AI services involves data transmission to external providers.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">8. Acceptable Use</h2>
              <p className="text-gray-700 mb-4">You agree not to:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
                <li>Use the Platform for any unlawful purpose or in violation of any applicable regulations</li>
                <li>Upload malicious code, viruses, or harmful files</li>
                <li>Attempt to gain unauthorized access to other accounts or systems</li>
                <li>Reverse engineer, decompile, or attempt to extract the source code of our software</li>
                <li>Use the Platform in a manner that could damage, disable, or impair service availability</li>
                <li>Exceed API rate limits or use automated tools to scrape data</li>
                <li>Upload Content that you do not have the right to process</li>
                <li>Share login credentials with unauthorized individuals</li>
              </ul>

              <h2 className="text-2xl font-bold mt-10 mb-4">9. Service Level and Availability</h2>
              <p className="text-gray-700 mb-4">
                We strive to maintain high availability of our services. While we target 99.5% monthly uptime, 
                we do not guarantee uninterrupted access to the Platform. Planned maintenance will be communicated 
                in advance when possible. Emergency maintenance may be performed without notice.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">10. Fees and Payment</h2>
              <p className="text-gray-700 mb-4">
                Subscription fees are billed in accordance with your selected plan. All fees are non-refundable except 
                as required by law. We reserve the right to change pricing with 30 days' notice. Failure to pay may 
                result in account suspension or termination.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">11. Intellectual Property</h2>
              <p className="text-gray-700 mb-4">
                ClarifyOps and its licensors retain all rights, title, and interest in the Platform, including all software, 
                algorithms, designs, trademarks, and documentation. These Terms do not grant you any rights to our intellectual 
                property except the limited right to use the Platform as described herein.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">12. Limitation of Liability</h2>
              <p className="text-gray-700 mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, CLARIFYOPS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
                SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, 
                BUSINESS OPPORTUNITIES, OR GOODWILL, ARISING FROM YOUR USE OF OR INABILITY TO USE THE PLATFORM.
              </p>
              <p className="text-gray-700 mb-4">
                OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING FROM THESE TERMS SHALL NOT EXCEED THE AMOUNT 
                YOU PAID TO CLARIFYOPS IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
              </p>
              <p className="text-gray-700 mb-4">
                Nothing in these Terms shall limit our liability for breaches of our obligations under HIPAA or any 
                applicable Business Associate Agreement.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">13. Indemnification</h2>
              <p className="text-gray-700 mb-4">
                You agree to indemnify and hold harmless ClarifyOps, its officers, directors, employees, and agents 
                from any claims, liabilities, damages, losses, or expenses (including reasonable legal fees) arising 
                from your use of the Platform, your violation of these Terms, or your violation of any applicable law 
                or regulation, including HIPAA.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">14. Termination</h2>
              
              <h3 className="text-xl font-semibold mt-6 mb-3">14.1 By You</h3>
              <p className="text-gray-700 mb-4">
                You may terminate your account at any time by contacting support@clarifyops.com. Upon termination, 
                you will have 30 days to export your data.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">14.2 By ClarifyOps</h3>
              <p className="text-gray-700 mb-4">
                We may suspend or terminate your access if you violate these Terms, fail to pay fees, or if continued 
                use poses a security risk. We will provide reasonable notice except in cases of urgent security concerns.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">14.3 Effect of Termination</h3>
              <p className="text-gray-700 mb-4">
                Upon termination, your license to use the Platform ceases. We will handle your data, including any PHI, 
                in accordance with our Privacy Policy, applicable BAA, and HIPAA requirements for data return or destruction.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">15. Disclaimers</h2>
              <p className="text-gray-700 mb-4">
                THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS 
                OR IMPLIED. AI-GENERATED OUTPUTS, INCLUDING DATA EXTRACTION RESULTS, FRAUD SCORES, AND CLAIM 
                CLASSIFICATIONS, ARE PROVIDED AS DECISION-SUPPORT TOOLS AND SHOULD NOT BE RELIED UPON AS THE SOLE 
                BASIS FOR CLAIMS DECISIONS. QUALIFIED HUMAN REVIEW IS RECOMMENDED FOR ALL CRITICAL DETERMINATIONS.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">16. Governing Law</h2>
              <p className="text-gray-700 mb-4">
                These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, 
                without regard to its conflict of law provisions. Any disputes arising from these Terms shall be 
                resolved in the state or federal courts located in Delaware.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">17. Changes to Terms</h2>
              <p className="text-gray-700 mb-4">
                We may modify these Terms at any time. Material changes will be communicated via email or through 
                a notice on the Platform at least 30 days before taking effect. Your continued use of the Platform 
                after changes take effect constitutes acceptance of the modified Terms.
              </p>

              <h2 className="text-2xl font-bold mt-10 mb-4">18. Miscellaneous</h2>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
                <li><strong>Severability:</strong> If any provision is found unenforceable, the remaining provisions remain in full force.</li>
                <li><strong>Waiver:</strong> Failure to enforce any right does not constitute a waiver of that right.</li>
                <li><strong>Assignment:</strong> You may not assign your rights without our written consent. We may assign our rights in connection with a merger, acquisition, or sale of assets.</li>
                <li><strong>Entire Agreement:</strong> These Terms, together with any applicable BAA and Privacy Policy, constitute the entire agreement between you and ClarifyOps.</li>
                <li><strong>Force Majeure:</strong> We are not liable for delays or failures caused by circumstances beyond our reasonable control.</li>
              </ul>

              <h2 className="text-2xl font-bold mt-10 mb-4">19. Contact Information</h2>
              <div className="bg-gray-50 rounded-xl p-6 not-prose">
                <p className="text-gray-700 mb-4">
                  For questions about these Terms of Service, please contact us:
                </p>
                <div className="space-y-2 text-gray-700">
                  <p><strong>Legal:</strong> <a href="mailto:legal@clarifyops.com" className="text-indigo-600 hover:underline">legal@clarifyops.com</a></p>
                  <p><strong>HIPAA/Compliance:</strong> <a href="mailto:compliance@clarifyops.com" className="text-indigo-600 hover:underline">compliance@clarifyops.com</a></p>
                  <p><strong>General Support:</strong> <a href="mailto:support@clarifyops.com" className="text-indigo-600 hover:underline">support@clarifyops.com</a></p>
                </div>
              </div>
            </motion.div>
          </div>
        </section>
      </main>

      <footer className="bg-gray-900 text-white py-8 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <img src="/logo.png" alt="ClarifyOps" className="h-6 brightness-0 invert" />
            <span className="text-gray-400 text-sm">&copy; 2026 ClarifyOps. All rights reserved.</span>
          </div>
          <div className="flex items-center gap-6 text-sm text-gray-400">
            <Link to="/trust" className="hover:text-white transition-colors">Trust Center</Link>
            <Link to="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link to="/security" className="hover:text-white transition-colors">Security</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
